name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: get file src git
      uses: actions/checkout@v4
    - name: compile
      run: |
        make
    - name: execute
      run: |
        ./generated/main.c
    - name: verify execution 
      run: |
        echo "Tada Programme Bien execute"
