name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: get file src git
      uses: actions/checkout@v4
    -name: Set up Cmake
      run: sudo apt-get update && sudo apt-get install -y cmake 
    - name: compile
      run: |
        mkdir build
        cd build
        cmake..
        cmake --build .
    - name: execute
      run: |
        cd build
        cd Release
        ./sobel
    - name: verify execution 
      run: |
        echo "Tada Programme Bien execute"
